package com.codearena.codearena.model;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.util.List;

/**
 * JPA entity representing a coding problem.
 *
 * <p>In Phase 4 this becomes a real database table. The mapping annotations:
 * <ul>
 *   <li>{@code @Entity} + {@code @Table(name = "problems")} — map the class to
 *       the {@code problems} table.</li>
 *   <li>{@code @Id} + {@code @GeneratedValue(IDENTITY)} — {@code id} is the
 *       primary key, generated by the database (auto-increment in H2,
 *       identity/serial in PostgreSQL).</li>
 *   <li>{@code @Enumerated(EnumType.STRING)} — store the difficulty as its name
 *       ("EASY"), not its ordinal. Storing the ordinal is fragile: reordering the
 *       enum would silently corrupt existing rows.</li>
 *   <li>{@code @ElementCollection} — {@code tags} is a collection of simple
 *       values, so Hibernate stores them in a side table ({@code problem_tags})
 *       linked by {@code problem_id}. Loaded eagerly because tags are small and
 *       always shown with a problem.</li>
 *   <li>{@code @Column(updatable = false)} on {@code createdAt} — the creation
 *       time is set once and never overwritten by an update.</li>
 * </ul>
 *
 * <p>Note we use {@code @Getter}/{@code @Setter} rather than Lombok's
 * {@code @Data} here. {@code @Data} also generates {@code equals}/{@code hashCode}
 * over all fields, which is discouraged for JPA entities (their identity is the
 * {@code @Id}, and including mutable/relationship fields can trigger surprising
 * behaviour and lazy-loading).
 */
@Entity
@Table(name = "problems")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Problem {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Difficulty difficulty;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "problem_tags", joinColumns = @JoinColumn(name = "problem_id"))
    @Column(name = "tag")
    private List<String> tags;

    @Column(nullable = false, updatable = false)
    private Instant createdAt;
}
